-- GENERATED by 03_cdc_migration/postgres/generate_seed.py. Do not edit by hand.
--
-- Seed data for the legacy fleet database. Runs once, on first start, after 01_schema.sql and
-- 02_roles.sh. Re-applying it never duplicates rows (ON CONFLICT DO NOTHING); on a later day it
-- would only backfill days since the first run, so it is meant for initialisation.
-- Debezium's initial snapshot publishes all of it as op = 'r' (read) events.

\set ON_ERROR_STOP on

INSERT INTO fleet.equipment (equipment_id, equipment_serial_number, type_name, category, manufacturer, model, commissioned_on, assigned_site, status, service_interval_hours)
VALUES
    (1, 'BOLT-001', 'Roof_Bolter', 'BEV', 'MacLean', '975 Roof Bolter EV', DATE '2020-09-01', 'SURFACE_SHOP', 'ACTIVE', 250),
    (2, 'BOLT-002', 'Roof_Bolter', 'BEV', 'MacLean', '975 Roof Bolter EV', DATE '2024-10-09', 'RAMP_NORTH', 'ACTIVE', 250),
    (3, 'BOLT-003', 'Roof_Bolter', 'Diesel', 'MacLean', '975 Roof Bolter', DATE '2018-02-23', 'RAMP_NORTH', 'ACTIVE', 250),
    (4, 'BOLT-004', 'Roof_Bolter', 'Diesel', 'MacLean', '975 Roof Bolter', DATE '2023-04-11', 'SURFACE_SHOP', 'ACTIVE', 250),
    (5, 'CABLE-001', 'Cable_Bolter', 'BEV', 'Epiroc', 'Cabletec LC Battery', DATE '2019-09-09', 'LEVEL_2600', 'ACTIVE', 250),
    (6, 'CABLE-002', 'Cable_Bolter', 'Diesel', 'Epiroc', 'Cabletec LC', DATE '2023-11-13', 'RAMP_NORTH', 'ACTIVE', 250),
    (7, 'CABLE-003', 'Cable_Bolter', 'Diesel', 'Epiroc', 'Cabletec LC', DATE '2018-09-20', 'LEVEL_2600', 'ACTIVE', 250),
    (8, 'JUMBO-001', 'Face_Drill_Jumbo', 'BEV', 'Epiroc', 'Boomer M2 Battery', DATE '2021-05-18', 'LEVEL_2400', 'ACTIVE', 250),
    (9, 'JUMBO-002', 'Face_Drill_Jumbo', 'BEV', 'Epiroc', 'Boomer M2 Battery', DATE '2024-09-02', 'RAMP_NORTH', 'ACTIVE', 250),
    (10, 'JUMBO-003', 'Face_Drill_Jumbo', 'Diesel', 'Epiroc', 'Boomer M2C', DATE '2022-06-06', 'SURFACE_SHOP', 'ACTIVE', 250),
    (11, 'JUMBO-004', 'Face_Drill_Jumbo', 'Diesel', 'Epiroc', 'Boomer M2C', DATE '2022-02-06', 'LEVEL_2400', 'ACTIVE', 250),
    (12, 'JUMBO-005', 'Face_Drill_Jumbo', 'Diesel', 'Epiroc', 'Boomer M2C', DATE '2020-11-22', 'RAMP_NORTH', 'ACTIVE', 250),
    (13, 'LH-DRILL-001', 'Longhole_Drill', 'BEV', 'Sandvik', 'DL422iE', DATE '2022-09-22', 'SURFACE_SHOP', 'ACTIVE', 250),
    (14, 'LH-DRILL-002', 'Longhole_Drill', 'BEV', 'Sandvik', 'DL422iE', DATE '2023-12-28', 'SURFACE_SHOP', 'ACTIVE', 250),
    (15, 'LH-DRILL-003', 'Longhole_Drill', 'Diesel', 'Sandvik', 'DL422i', DATE '2021-10-11', 'LEVEL_2400', 'MAINTENANCE', 250),
    (16, 'LH-DRILL-004', 'Longhole_Drill', 'Diesel', 'Sandvik', 'DL422i', DATE '2019-10-31', 'LEVEL_2800', 'STANDBY', 250),
    (17, 'SCOOP-001', 'Scooptram_LHD', 'BEV', 'Epiroc', 'Scooptram ST14 Battery', DATE '2024-05-20', 'LEVEL_2400', 'ACTIVE', 500),
    (18, 'SCOOP-002', 'Scooptram_LHD', 'BEV', 'Epiroc', 'Scooptram ST14 Battery', DATE '2024-06-07', 'LEVEL_2800', 'ACTIVE', 500),
    (19, 'SCOOP-003', 'Scooptram_LHD', 'BEV', 'Epiroc', 'Scooptram ST14 Battery', DATE '2023-06-04', 'LEVEL_2400', 'ACTIVE', 500),
    (20, 'SCOOP-004', 'Scooptram_LHD', 'Diesel', 'Epiroc', 'Scooptram ST14', DATE '2019-09-10', 'LEVEL_2400', 'ACTIVE', 500),
    (21, 'SCOOP-005', 'Scooptram_LHD', 'Diesel', 'Epiroc', 'Scooptram ST14', DATE '2019-05-03', 'LEVEL_2400', 'ACTIVE', 500),
    (22, 'SCOOP-006', 'Scooptram_LHD', 'Diesel', 'Epiroc', 'Scooptram ST14', DATE '2022-03-28', 'SURFACE_SHOP', 'ACTIVE', 500),
    (23, 'TRUCK-001', 'Mine_Truck_Hauler', 'BEV', 'Sandvik', 'TH665B', DATE '2021-02-17', 'SURFACE_SHOP', 'ACTIVE', 500),
    (24, 'TRUCK-002', 'Mine_Truck_Hauler', 'BEV', 'Sandvik', 'TH665B', DATE '2018-01-30', 'LEVEL_2400', 'ACTIVE', 500),
    (25, 'TRUCK-003', 'Mine_Truck_Hauler', 'Diesel', 'Sandvik', 'TH545i', DATE '2020-03-19', 'RAMP_NORTH', 'ACTIVE', 500),
    (26, 'TRUCK-004', 'Mine_Truck_Hauler', 'Diesel', 'Sandvik', 'TH545i', DATE '2018-06-23', 'LEVEL_2800', 'ACTIVE', 500),
    (27, 'TRUCK-005', 'Mine_Truck_Hauler', 'Diesel', 'Sandvik', 'TH545i', DATE '2022-03-28', 'RAMP_NORTH', 'ACTIVE', 500),
    (28, 'ANFO-001', 'Anfoloader_Emulsion', 'BEV', 'Normet', 'Charmec MC 605 VE SD', DATE '2024-09-05', 'SURFACE_SHOP', 'ACTIVE', 250),
    (29, 'ANFO-002', 'Anfoloader_Emulsion', 'Diesel', 'Normet', 'Charmec MC 605 VE', DATE '2023-09-08', 'LEVEL_2800', 'ACTIVE', 250),
    (30, 'ANFO-003', 'Anfoloader_Emulsion', 'Diesel', 'Normet', 'Charmec MC 605 VE', DATE '2020-08-31', 'LEVEL_2800', 'ACTIVE', 250),
    (31, 'LIFT-001', 'Scissor_Lift', 'BEV', 'Normet', 'Utilift MF 540 SD', DATE '2021-05-26', 'SURFACE_SHOP', 'ACTIVE', 250),
    (32, 'LIFT-002', 'Scissor_Lift', 'BEV', 'Normet', 'Utilift MF 540 SD', DATE '2024-07-03', 'LEVEL_2800', 'ACTIVE', 250),
    (33, 'LIFT-003', 'Scissor_Lift', 'Diesel', 'Normet', 'Utilift MF 540', DATE '2019-06-30', 'LEVEL_2400', 'ACTIVE', 250),
    (34, 'LIFT-004', 'Scissor_Lift', 'Diesel', 'Normet', 'Utilift MF 540', DATE '2021-12-16', 'LEVEL_2800', 'ACTIVE', 250),
    (35, 'SCALE-001', 'Scaler', 'BEV', 'MacLean', 'SS3 Scaler EV', DATE '2023-06-29', 'LEVEL_2400', 'ACTIVE', 250),
    (36, 'SCALE-002', 'Scaler', 'Diesel', 'MacLean', 'SS3 Scaler', DATE '2018-03-29', 'LEVEL_2800', 'ACTIVE', 250),
    (37, 'SCALE-003', 'Scaler', 'Diesel', 'MacLean', 'SS3 Scaler', DATE '2024-08-24', 'SURFACE_SHOP', 'ACTIVE', 250),
    (38, 'GRADE-001', 'Underground_Grader', 'BEV', 'Getman', 'A64 Grader Batt-MEC', DATE '2021-07-04', 'LEVEL_2800', 'ACTIVE', 500),
    (39, 'GRADE-002', 'Underground_Grader', 'Diesel', 'Getman', 'A64 Grader', DATE '2022-03-25', 'LEVEL_2400', 'ACTIVE', 500),
    (40, 'GRADE-003', 'Underground_Grader', 'Diesel', 'Getman', 'A64 Grader', DATE '2024-05-20', 'LEVEL_2600', 'ACTIVE', 500)
ON CONFLICT (equipment_id) DO NOTHING;

-- 90 days of end-of-shift hour-meter readings per machine, ending yesterday. Working
-- machines add 6-20 hours a day; machines in the shop or on standby add 0-2.
SELECT setseed(0.3);

WITH starting (equipment_id, starting_hours) AS (
    VALUES
        (1, 2235.9),
        (2, 1383.5),
        (3, 1856.1),
        (4, 2533.8),
        (5, 3630.5),
        (6, 3080.0),
        (7, 2855.1),
        (8, 1954.4),
        (9, 3779.1),
        (10, 3819.6),
        (11, 2585.7),
        (12, 3594.6),
        (13, 2807.3),
        (14, 1850.7),
        (15, 3974.8),
        (16, 3733.1),
        (17, 1791.1),
        (18, 1377.7),
        (19, 1386.5),
        (20, 3352.6),
        (21, 3332.6),
        (22, 3666.5),
        (23, 1300.8),
        (24, 2699.6),
        (25, 1937.4),
        (26, 3884.2),
        (27, 2656.2),
        (28, 3924.1),
        (29, 3216.9),
        (30, 1923.1),
        (31, 3407.5),
        (32, 2924.2),
        (33, 2130.9),
        (34, 1981.0),
        (35, 3873.6),
        (36, 2477.7),
        (37, 2219.1),
        (38, 1939.6),
        (39, 1275.4),
        (40, 1823.1)
),
daily AS (
    SELECT e.equipment_id,
           s.starting_hours,
           (current_date - d.days_ago) + time '18:00' AS reading_at,
           CASE WHEN e.status = 'ACTIVE' THEN 6 + random() * 14 ELSE random() * 2 END AS hours_added
    FROM fleet.equipment e
    JOIN starting s USING (equipment_id)
    CROSS JOIN generate_series(90, 1, -1) AS d (days_ago)
    ORDER BY e.equipment_id, reading_at
)
INSERT INTO fleet.hour_meter_logs (equipment_id, reading_at, hour_meter, source, recorded_by)
SELECT equipment_id,
       reading_at AT TIME ZONE 'UTC',
       round((starting_hours + SUM(hours_added) OVER w)::numeric, 1),
       -- Every 10th day the reading comes from a service visit instead of the shift report.
       CASE WHEN row_number() OVER w % 10 = 0 THEN 'SERVICE_VISIT' ELSE 'SHIFT_REPORT' END,
       CASE WHEN row_number() OVER w % 10 = 0 THEN 'maintenance_planner' ELSE 'shift_supervisor' END
FROM daily
WINDOW w AS (PARTITION BY equipment_id ORDER BY reading_at)
ON CONFLICT (equipment_id, reading_at) DO NOTHING;

ANALYZE fleet.equipment;
ANALYZE fleet.hour_meter_logs;
