"""Creates the RSA key pair the Snowflake connector authenticates with, and wires it up locally.

Idempotent: an existing key pair is reused unless --rotate is passed. Each run:
  1. ensures secrets/snowflake_rsa_key.p8 (private, PKCS#8) and .pub exist (both gitignored),
  2. sets SNOWFLAKE_PRIVATE_KEY in .env to the key body the connector expects
     (no header/footer, no line breaks),
  3. renders setup.sql to secrets/snowflake_setup.sql with the public key filled in.

Usage (from the repo root):
    python 02_streaming_ingestion/snowflake/generate_keypair.py [--rotate]
"""

import argparse
import re
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

REPO_ROOT = Path(__file__).resolve().parents[2]
SECRETS_DIR = REPO_ROOT / "secrets"
PRIVATE_KEY_PATH = SECRETS_DIR / "snowflake_rsa_key.p8"
PUBLIC_KEY_PATH = SECRETS_DIR / "snowflake_rsa_key.pub"
RENDERED_SQL_PATH = SECRETS_DIR / "snowflake_setup.sql"
SETUP_SQL_TEMPLATE = Path(__file__).resolve().parent / "setup.sql"
ENV_PATH = REPO_ROOT / ".env"
ENV_EXAMPLE_PATH = REPO_ROOT / ".env.example"
ENV_VAR = "SNOWFLAKE_PRIVATE_KEY"


def pem_body(pem: str) -> str:
    """Strip the BEGIN/END lines and line breaks, leaving the base64 key body."""
    return "".join(line.strip() for line in pem.splitlines() if line.strip() and not line.startswith("-----"))


def write_key_pair() -> None:
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    private_pem = key.private_bytes(
        serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8, serialization.NoEncryption()
    )
    public_pem = key.public_key().public_bytes(
        serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo
    )
    SECRETS_DIR.mkdir(exist_ok=True)
    PRIVATE_KEY_PATH.write_bytes(private_pem)
    PUBLIC_KEY_PATH.write_bytes(public_pem)
    try:
        PRIVATE_KEY_PATH.chmod(0o600)
    except OSError:
        pass  # Not supported on every filesystem (e.g. Windows); the file is gitignored either way.


def set_env_var(env_path: Path, name: str, value: str) -> None:
    """Set name=value in a dotenv file, replacing an existing line or appending one."""
    if not env_path.exists():
        # Start from the example so every other setting is present too.
        text = ENV_EXAMPLE_PATH.read_text(encoding="utf-8") if ENV_EXAMPLE_PATH.exists() else ""
    else:
        text = env_path.read_text(encoding="utf-8")
    line = f"{name}={value}"
    pattern = re.compile(rf"^{re.escape(name)}=.*$", re.MULTILINE)
    if pattern.search(text):
        text = pattern.sub(lambda _: line, text)
    else:
        text = text.rstrip("\n") + f"\n{line}\n"
    env_path.write_text(text, encoding="utf-8")


def render_setup_sql(public_key_body: str) -> None:
    sql = SETUP_SQL_TEMPLATE.read_text(encoding="utf-8").replace("<RSA_PUBLIC_KEY>", public_key_body)
    header = "-- GENERATED by generate_keypair.py from 02_streaming_ingestion/snowflake/setup.sql. Do not edit.\n"
    RENDERED_SQL_PATH.write_text(header + sql, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--rotate", action="store_true", help="replace the existing key pair")
    args = parser.parse_args()

    if args.rotate or not PRIVATE_KEY_PATH.exists():
        write_key_pair()
        print(f"Generated a new key pair in {SECRETS_DIR.relative_to(REPO_ROOT)}/")
        if args.rotate:
            print("Rotated: re-run secrets/snowflake_setup.sql in Snowflake, then restart Kafka Connect.")
    else:
        print(f"Reusing existing key pair in {SECRETS_DIR.relative_to(REPO_ROOT)}/")

    set_env_var(ENV_PATH, ENV_VAR, pem_body(PRIVATE_KEY_PATH.read_text(encoding="ascii")))
    print(f"Set {ENV_VAR} in .env")

    render_setup_sql(pem_body(PUBLIC_KEY_PATH.read_text(encoding="ascii")))
    print(f"Rendered {RENDERED_SQL_PATH.relative_to(REPO_ROOT)}: run it in Snowsight as ACCOUNTADMIN")


if __name__ == "__main__":
    main()
