"""Creates the RSA key pair dbt authenticates to Snowflake with, and wires it up locally.

Same flow as the connector's key (02_streaming_ingestion/snowflake/generate_keypair.py), with its
own files and variable, so the dbt user and the connector never share a key. Idempotent: an
existing key pair is reused unless --rotate is passed. Each run:
  1. ensures secrets/snowflake_dbt_rsa_key.p8 (private, PKCS#8) and .pub exist (both gitignored),
  2. sets DBT_SNOWFLAKE_PRIVATE_KEY in .env to the base64 key body dbt-snowflake accepts,
  3. renders setup.sql to secrets/snowflake_dbt_setup.sql with the public key filled in.

Usage (from the repo root):
    python 04_data_warehouse/snowflake/generate_dbt_keypair.py [--rotate]
"""

import argparse
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "02_streaming_ingestion" / "snowflake"))

from generate_keypair import pem_body, set_env_var  # noqa: E402

SECRETS_DIR = REPO_ROOT / "secrets"
PRIVATE_KEY_PATH = SECRETS_DIR / "snowflake_dbt_rsa_key.p8"
PUBLIC_KEY_PATH = SECRETS_DIR / "snowflake_dbt_rsa_key.pub"
RENDERED_SQL_PATH = SECRETS_DIR / "snowflake_dbt_setup.sql"
SETUP_SQL_TEMPLATE = Path(__file__).resolve().parent / "setup.sql"
ENV_PATH = REPO_ROOT / ".env"
ENV_VAR = "DBT_SNOWFLAKE_PRIVATE_KEY"


def write_key_pair() -> None:
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    SECRETS_DIR.mkdir(exist_ok=True)
    PRIVATE_KEY_PATH.write_bytes(
        key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8, serialization.NoEncryption())
    )
    PUBLIC_KEY_PATH.write_bytes(
        key.public_key().public_bytes(serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo)
    )
    try:
        PRIVATE_KEY_PATH.chmod(0o600)
    except OSError:
        pass  # Not supported on every filesystem (e.g. Windows); the file is gitignored either way.


def render_setup_sql(public_key_body: str) -> str:
    sql = SETUP_SQL_TEMPLATE.read_text(encoding="utf-8").replace("<RSA_PUBLIC_KEY>", public_key_body)
    header = "-- GENERATED by generate_dbt_keypair.py from 04_data_warehouse/snowflake/setup.sql. Do not edit.\n"
    return header + sql


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--rotate", action="store_true", help="replace the existing key pair")
    args = parser.parse_args()

    if args.rotate or not PRIVATE_KEY_PATH.exists():
        write_key_pair()
        print(f"Generated a new key pair in {SECRETS_DIR.relative_to(REPO_ROOT)}/")
        if args.rotate:
            print("Rotated: re-run secrets/snowflake_dbt_setup.sql in Snowflake, then re-run kubernetes/deploy.sh.")
    else:
        print(f"Reusing existing key pair in {SECRETS_DIR.relative_to(REPO_ROOT)}/")

    set_env_var(ENV_PATH, ENV_VAR, pem_body(PRIVATE_KEY_PATH.read_text(encoding="ascii")))
    print(f"Set {ENV_VAR} in .env")

    RENDERED_SQL_PATH.write_text(render_setup_sql(pem_body(PUBLIC_KEY_PATH.read_text(encoding="ascii"))), encoding="utf-8")
    print(f"Rendered {RENDERED_SQL_PATH.relative_to(REPO_ROOT)}: run it in Snowsight as ACCOUNTADMIN")


if __name__ == "__main__":
    main()
