"""Renders postgres/init/03_seed.sql: the legacy database's equipment master data and hour-meter history.

The fleet itself (ids, serial numbers, types, BEV/Diesel) comes from the telemetry simulator's
equipment_config.py, so the legacy database and the telemetry stream describe the same 40 machines.
Legacy-only attributes (manufacturer, model, commissioning date, site, status) are derived
deterministically, so re-rendering produces the same file. A unit test fails if the committed
file is out of date.

The hour-meter history (90 days of daily shift reports) is generated inside Postgres, relative to
the day the database is initialised, so the file stays small and the history ends "yesterday".

Usage (from the repo root):
    python 03_cdc_migration/postgres/generate_seed.py
"""

import random
import sys
from datetime import date, timedelta
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "01_telemetry_simulator"))

from equipment_config import EQUIPMENT_FLEET  # noqa: E402

SEED_SQL_PATH = Path(__file__).resolve().parent / "init" / "03_seed.sql"
SEED = 3
HISTORY_DAYS = 90

# type_name -> (manufacturer, diesel model, battery-electric model, service interval hours)
MODELS = {
    "Roof_Bolter": ("MacLean", "975 Roof Bolter", "975 Roof Bolter EV", 250),
    "Cable_Bolter": ("Epiroc", "Cabletec LC", "Cabletec LC Battery", 250),
    "Face_Drill_Jumbo": ("Epiroc", "Boomer M2C", "Boomer M2 Battery", 250),
    "Longhole_Drill": ("Sandvik", "DL422i", "DL422iE", 250),
    "Scooptram_LHD": ("Epiroc", "Scooptram ST14", "Scooptram ST14 Battery", 500),
    "Mine_Truck_Hauler": ("Sandvik", "TH545i", "TH665B", 500),
    "Anfoloader_Emulsion": ("Normet", "Charmec MC 605 VE", "Charmec MC 605 VE SD", 250),
    "Scissor_Lift": ("Normet", "Utilift MF 540", "Utilift MF 540 SD", 250),
    "Scaler": ("MacLean", "SS3 Scaler", "SS3 Scaler EV", 250),
    "Underground_Grader": ("Getman", "A64 Grader", "A64 Grader Batt-MEC", 500),
}
SITES = ["LEVEL_2400", "LEVEL_2600", "LEVEL_2800", "RAMP_NORTH", "SURFACE_SHOP"]
# Most of the fleet is working; a few machines start in the shop or parked.
STATUS_WEIGHTS = {"ACTIVE": 34, "MAINTENANCE": 4, "STANDBY": 2}
COMMISSIONED_FROM, COMMISSIONED_TO = date(2018, 1, 1), date(2024, 12, 31)


def equipment_rows(rng: random.Random) -> list[dict]:
    rows = []
    for machine in EQUIPMENT_FLEET:
        manufacturer, diesel_model, bev_model, service_interval = MODELS[machine["type_name"]]
        span = (COMMISSIONED_TO - COMMISSIONED_FROM).days
        rows.append({
            **machine,
            "manufacturer": manufacturer,
            "model": bev_model if machine["category"] == "BEV" else diesel_model,
            "commissioned_on": COMMISSIONED_FROM + timedelta(days=rng.randrange(span)),
            "assigned_site": rng.choice(SITES),
            "status": rng.choices(list(STATUS_WEIGHTS), weights=list(STATUS_WEIGHTS.values()))[0],
            "service_interval_hours": service_interval,
            # Hour meter 90 days ago: roughly in line with the simulator's engine-hour range.
            "starting_hours": round(rng.uniform(1200, 4000), 1),
        })
    return rows


def sql_literal(value) -> str:
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    if isinstance(value, date):
        return f"DATE '{value.isoformat()}'"
    return str(value)


def render(rows: list[dict]) -> str:
    columns = [
        "equipment_id", "equipment_serial_number", "type_name", "category", "manufacturer", "model",
        "commissioned_on", "assigned_site", "status", "service_interval_hours",
    ]
    values = ",\n".join(
        "    (" + ", ".join(sql_literal(row[c]) for c in columns) + ")" for row in rows
    )
    starting = ",\n".join(f"        ({row['equipment_id']}, {row['starting_hours']})" for row in rows)
    return f"""\
-- GENERATED by 03_cdc_migration/postgres/generate_seed.py. Do not edit by hand.
--
-- Seed data for the legacy fleet database. Runs once, on first start, after 01_schema.sql and
-- 02_roles.sh. Re-applying it never duplicates rows (ON CONFLICT DO NOTHING); on a later day it
-- would only backfill days since the first run, so it is meant for initialisation.
-- Debezium's initial snapshot publishes all of it as op = 'r' (read) events.

\\set ON_ERROR_STOP on

INSERT INTO fleet.equipment ({", ".join(columns)})
VALUES
{values}
ON CONFLICT (equipment_id) DO NOTHING;

-- {HISTORY_DAYS} days of end-of-shift hour-meter readings per machine, ending yesterday. Working
-- machines add 6-20 hours a day; machines in the shop or on standby add 0-2.
SELECT setseed(0.{SEED});

WITH starting (equipment_id, starting_hours) AS (
    VALUES
{starting}
),
daily AS (
    SELECT e.equipment_id,
           s.starting_hours,
           (current_date - d.days_ago) + time '18:00' AS reading_at,
           CASE WHEN e.status = 'ACTIVE' THEN 6 + random() * 14 ELSE random() * 2 END AS hours_added
    FROM fleet.equipment e
    JOIN starting s USING (equipment_id)
    CROSS JOIN generate_series({HISTORY_DAYS}, 1, -1) AS d (days_ago)
    ORDER BY e.equipment_id, reading_at
)
INSERT INTO fleet.hour_meter_logs (equipment_id, reading_at, hour_meter, source, recorded_by)
SELECT equipment_id,
       reading_at AT TIME ZONE 'UTC',
       round((starting_hours + SUM(hours_added) OVER w)::numeric, 1),
       -- Every 10th day the reading comes from a service visit instead of the shift report.
       CASE WHEN row_number() OVER w % 10 = 0 THEN 'SERVICE_VISIT' ELSE 'SHIFT_REPORT' END,
       CASE WHEN row_number() OVER w % 10 = 0 THEN 'maintenance_planner' ELSE 'shift_supervisor' END
FROM daily
WINDOW w AS (PARTITION BY equipment_id ORDER BY reading_at)
ON CONFLICT (equipment_id, reading_at) DO NOTHING;

ANALYZE fleet.equipment;
ANALYZE fleet.hour_meter_logs;
"""


def main() -> None:
    SEED_SQL_PATH.write_text(render(equipment_rows(random.Random(SEED))), encoding="utf-8", newline="\n")
    print(f"Wrote {SEED_SQL_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
